# Source: strimzi/templates/kafka.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: vnoc
  namespace: strimzi
  labels:
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-name: "vnoc"
    meta.helm.sh/release-namespace: "strimzi"
spec:
  entityOperator:
    topicOperator:
      resources:
        limits:
          cpu: 300m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi
    userOperator:
      resources:
        limits:
          cpu: 300m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi
  kafka:
    config:
      auto.create.topics.enable: false
      message.max.bytes: 5242880
      offsets.topic.replication.factor: 1
      replica.fetch.max.bytes: 5242880
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
      min.insync.replicas: 1
    jvmOptions:
      -Xms: 512m
      -Xmx: 512m
    listeners:
      - authentication:
          type: tls
        name: internal
        port: 9092
        tls: true
        type: internal
    replicas: 1
    resources:
      limits:
        cpu: 200m
        memory: 1024Mi

      requests:
        cpu: 100m
        memory: 1024Mi
    storage:
      size: 256Mi
      type: persistent-claim
      deleteClaim: false
    template:
      externalBootstrapService:
        metadata:
          annotations:
            loadbalancer.openstack.org/floating-subnet: ext-ha-v4
            loadbalancer.openstack.org/proxy-protocol: "false"
      perPodService:
        metadata:
          annotations:
            loadbalancer.openstack.org/floating-subnet: ext-ha-v4
            loadbalancer.openstack.org/proxy-protocol: "false"
      pod:
        securityContext:
          fsGroup: 2000
    version: 3.5.1

  zookeeper:
    jvmOptions:
      -Xms: 256m
      -Xmx: 256m
    replicas: 1
    resources:
      limits:
        cpu: 300m
        memory: 256Mi
      requests:
        cpu: 150m
        memory: 256Mi
    storage:
      size: 256Mi
      type: persistent-claim
      deleteClaim: false
    template:
      pod:
        securityContext:
          fsGroup: 2000
