apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi
  namespace: strimzi
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://strimzi.io/charts/
    targetRevision: {{ .Values.strimzi.targetRevision }}
    chart: "strimzi-kafka-operator"
    helm:
      parameters: []
      releaseName: strimzi
      valueFiles:
        - values.yaml
      values: |
        namespace: strimzi
        targetRevision: 0.34.0
        values:
          featureGates: "-UseStrimziPodSets"
          watchAnyNamespace: true
      version: v3
