apiVersion: v2
name: sampo-strimzi-kafka-operator
description: A Helm chart for Kubernetes

type: application
version: 0.34.0

dependencies:
  - name: strimzi-kafka-operator
    version: 0.34.0
    repository: https://strimzi.io/charts/
