strimzi-kafka-operator:
  image:
    imagePullSecrets: quay-registry
  watchAnyNamespace: true
  resources:
    limits:
      memory: 1536Mi
      cpu: 500m
    requests:
      memory: 1536Mi
      cpu: 200m
  extraEnvs:
    - name: JAVA_OPTS
      value: "-Xms1024m -Xmx1024m"
  podSecurityContext:
    runAsNonRoot: true
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
        - ALL
